name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - using: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        using: docker/build-push-action@v1
        with:
          username: vjburic1
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: vjburic1/publish-packages/game
          tag_with_sha: true
